List<String> fortaleza_bairros = [
  "Aerolândia",
  "Aeroporto",
  "Aldeota",
  "Alvorada",
  "Amadeu Furtado",
  "Ancuri",
  "Antonio Bezerra",
  "Autran Nunes",
  "Barra do Ceará",
  "Barroso",
  "Bela Vista",
  "Benfica",
  "Boa Vista",
  "Bom Futuro",
  "Bom Jardim",
  "Bonsucesso",
  "Cais do Porto",
  "Cajazeiras",
  "Cambeba",
  "Canindezinho",
  "Carlito Pamplona",
  "Centro",
  "Cidade 2000",
  "Cidade dos Funcionários",
  "Cocó",
  "Coqueirinho",
  "Conjunto Ceará I",
  "Conjunto Ceará II",
  "Conjunto Esperança",
  "Conjunto Palmeiras",
  "Couto Fernandes",
  "Cristo Redentor",
  "Curió",
  "Damas",
  "De Lourdes",
  "Demócrito Rocha",
  "Dendê",
  "Dias Macedo",
  "Dionísio Torres",
  "Dom Lustosa",
  "Dunas",
  "Edson Queiroz",
  "Engenheiro Luciano Cavalcante",
  "Farias Brito",
  "Fátima",
  "Floresta",
  "Genibaú",
  "Granja Lisboa",
  "Granja Portugal",
  "Guajeru",
  "Guararapes",
  "Henrique Jorge",
  "Itaoca",
  "Itaperi",
  "Jacarecanga",
  "Jangurussu",
  "Jardim América",
  "Jardim das Oliveiras",
  "Jardim Guanabara",
  "Jardim Iracema",
  "Joaquim Távora",
  "João XXIII",
  "José de Alencar",
  "José Walter",
  "Luciano Cavalcante",
  "Manuel Dias Branco",
  "Manoel Sátiro",
  "Maraponga",
  "Meireles",
  "Messejana",
  "Mondubim",
  "Montese",
  "Mucuripe",
  "Olavo Oliveira",
  "Panamericano",
  "Papicu",
  "Parangaba",
  "Parque Araxá",
  "Parque Dois Irmãos",
  "Parque Iracema",
  "Parque Manibura",
  "Parque Santa Rosa",
  "Parque São José",
  "Parreão",
  "Passaré",
  "Paupina",
  "Pedras",
  "Pici",
  "Pirambu",
  "Planalto Ayrton Senna",
  "Planalto Pici",
  "Praia de Iracema",
  "Praia do Futuro I",
  "Praia do Futuro II",
  "Presidente Kennedy",
  "Prefeito José Walter",
  "Quintino Cunha",
  "Rachel de Queiroz",
  "Rodolfo Teófilo",
  "Sabiaguaba",
  "Salinas",
  "Santa Cecília",
  "Santa Maria",
  "Santa Rosa",
  "Santo Amaro",
  "Santos Dumont",
  "Sapiranga",
  "Serrinha",
  "São Bento",
  "São Gerardo",
  "São João do Tauape",
  "Siqueira",
  "Tabapuá",
  "Tauape",
  "Terras Belas",
  "Varjota",
  "Vicentina",
  "Vicente Pinzón",
  "Vila Ellery",
  "Vila Manoel Sátiro",
  "Vila Peri",
  "Vila União",
  "Vila Velha",
];
